### PR TITLE
Dashboard page

### PR DESCRIPTION
**Pull request by CalvinRodo**
Implemented a dashboard page to allow medical professionals to enter the information in any order. 

https://trello.com/c/eYk0GRz8/479-implement-medical-professionals-are-able-to-complete-the-medical-report-in-any-order

## Test

1. Click on "Lets Go" from the start page and it should bring you to the dashboard
1. Fill out any of the following sections: 
    - Basic Patient Information
    - Medical Conditions
    - Medications
    - Treatments
    - Supporting Documents
    - Your information and Declaration
1. The value *Not Completed* should change to *Completed* when the section is filled out properly

## Please Note: 

The following things **are not implemented**

- Consent link for PDF
- Claim 85$ compensation link 
- Save and return later
- Submit to service Canada
- Functional Limitations section
- Future Work Capacity
- Supporting Documents

### CODE REVIEW

**Comment by keithiopia** [comment]
Is this deployed anywhere for review?

**Comment by jeffmaher** [comment]
Here's a deployed link:
https://cppd-medical-dashboard-tdqnzle.herokuapp.com/

**Comment by dsamojlenko** [comment]
Something weird with the validation ... I added a Condition, Medication, and a Treatment, then went through and deleted all of them, and the sections still show as completed:

image

**Comment by dsamojlenko** [comment]
Should the Treatment and Medication links be disabled if there are no Conditions added? Maybe this is a question for @keithiopia?

**Comment by CalvinRodo** [comment]
> Something weird with the validation ... I added a Condition, Medication, and a Treatment, then went through and deleted all of them, and the sections still show as completed:
> 
> image

weird, it should validate with data in session I'll take a look at what's happening here.

**Comment by dsamojlenko** [comment]
ignore my other comment, I forgot about the add-condition-in-place thing .... will be working on that shortly.

**Comment by keithiopia** [comment]
> Should the Treatment and Medication links be disabled if there are no Conditions added? Maybe this is a question for @keithiopia?

The behaviour we're aiming for is that users can do any section first, so even medications before conditions.

**Comment by jeffmaher** [comment]
@CalvinRodo : Added #62, in case it helps with the navigation stuff. If not, feel free to ignore that PR.

**Comment by jeffmaher** [comment]
Might be missing from the design, but the Employment section isn't on the dashboard.

**Comment by CalvinRodo** [comment]
@jeffmaher Employment and Health weren't in the design for the dashboard. 

@keithiopia @michellengaiCDS  Can we add something for the case where there are no treatments.

@kylejones-ESDC What type of items can have no data entered, I'm assuming conditions is not one of them, is it just treatments or can it be medication as well?

**Comment by kylejones-ESDC** [comment]
> @kylejones-ESDC What type of items can have no data entered, I'm assuming conditions is not one of them, is it just treatments or can it be medication as well?

Medications too.  Unlikely, but not implausible.

**Comment by kylejones-ESDC** [comment]
> Should the Treatment and Medication links be disabled if there are no Conditions added? Maybe this is a question for @keithiopia?

That might be a good idea.  We would rather they not go ahead and complete medications without first considering the condition.

**Pull request merged**
