### PR TITLE
Medical professionals can view patient's consent form

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

Implementation of [showing the patient's consent](https://trello.com/c/WvIsBJ0J) to a medical professional.

# Test

1. Launch the application
1. Fill out the patient sections (personal, consent)
1. Click on 'View their consent form'

# Notes

- There was no Figma design for this page, so this is a best effort
- Removed mention of "PDF" from the "View consent" link on the dashboard, since it's not a PDF and not sure why it needs to be a PDF
- Future feature: If an applicant does not consent, no code should be generated and the application should be submitted as is. (i.e. a medical professional would never view a "do not consent" page, even though that can happen now)

### CODE REVIEW

**Comment by jeffmaher** [comment]
@sidewalkballet : Here's a quick one for a design review.

**Review by courtneycl — COMMENTED** [review]
"Note: Failure to check an option below could result in a delay in processing your application." should be removed from the view consent page, otherwise it's good!

**Comment by jeffmaher** [comment]
^ On it. Will ping when updated content fix is in.

**Comment by jeffmaher** [comment]
@sidewalkballet : Removed "Note: Failure..." text.

**Review by courtneycl — APPROVED** [review]
🐧

**Pull request merged**
