### PR TITLE
Supporting documents database

### PR DESCRIPTION
**Pull request by dsamojlenko**
# What this does
Integrates the SupportingDocuments section with the database.
- Create model and relationships
- Build out API endpoints for vue component to read from/write to

## Notes
- We are still not actually uploading files yet
- The API does not have any authentication, in fact we're relying on an active session in this case.
- Does NOT include document upload on Condition add/edit - there's another PR for that

### CODE REVIEW

**Comment by jeffmaher** [comment]
Taking a look now.

**Comment by jeffmaher** [comment]
Actually taking a look now. Sorry for the delay! :octocat:

**Comment by CalvinRodo** [comment]
I received a 500 error when attempting to save the data on the first page, could something have crashed the db in Heroku?

**Comment by jeffmaher** [comment]
@CalvinRodo : It looks like this may need a re-sync with the parent branch, as it doesn't have the Heroku DB and Redis stuff in it.

**Pull request merged**
