### PR TITLE
PostgreSQL and Redis for Review Environments

### PR DESCRIPTION
**Pull request by jeffmaher**
# Description

This sets up review environments with a PostgreSQL database for data and Redis for session storage.

# Test

To test, two things:

1) Login to Heroku and see PostgreSQL and Redis for [this environment](https://dashboard.heroku.com/apps/cppd-medical-heroku-rev-ptanp5)
2) Go to the review environment deployment and complete the personal section (if it doesn't work, the app will send a `HTTP 500` error.

### CODE REVIEW

**Comment by dsamojlenko** [comment]
I would lean towards Calvin's suggestion on this - we can just use the connection string directly in Sails, rather than parsing it out:

image

https://sailsjs.com/documentation/reference/configuration/sails-config-datastores

**Comment by jeffmaher** [comment]
Oh awesome! Didn't realize the Sequelize hook would take a URL (its documentation didn't show it). Will simplify it so that we just pass the connection string so we don't need all that additional code.

**Comment by dsamojlenko** [comment]
@jeffmaher it might be worth creating a staging-specific config in config/env/ for this?

**Comment by jeffmaher** [comment]
@dsamojlenko : I'm hesitant to commit any files that have environment-specific things. Worried about making the app less portable.

**Comment by jeffmaher** [comment]
@CalvinRodo @dsamojlenko : Thanks for the feedback on this. Much simpler now (and I think averts the need for a staging specific config). I do think we'll need to figure out how to handle config/config.json though, which we aren't using ATM, but migrations will eventually.

**Pull request merged**
