### PR TITLE
Functional Limitations

### PR DESCRIPTION
**Pull request by CalvinRodo**
Adding Functional Limitations page and connecting it with the rest of the application. 

**Please Note** Error Messages still need functionality to add patientName not currently implemented

### CODE REVIEW

**Comment by jeffmaher** [comment]
@sidewalkballet : Can you do the design review on this one?

**Review by courtneycl — COMMENTED** [review]
* `Cancel` gives a 400; should go back to the dashboard without saving any entries.

* `Continue` button should say `Save`

* Missing errors on height and weight: 
image

* Teeny string issues; missing a `'s` and spacing: 
image

**Comment by sidewalkballet** [comment]
I think the `Cancel` button is a high priority but the rest can be bugs for later.

**Comment by sidewalkballet** [comment]
Actually, per figma, there should be no cancel option.

**Comment by CalvinRodo** [comment]
All issues identified by @sidewalkballet should be fixed.

**Review by courtneycl — DISMISSED** [review]
spaces are still there but that can be addressed later 💃

**Review by dsamojlenko — APPROVED** [review]

**Pull request merged**
