### PR TITLE
This fixes the case on a single en string

### PR DESCRIPTION
**Pull request by keithiopia**
Minor case correction to `dashboard.basic_info`.
The diff will be horrible because it switches from double-space to tab (or the other way around). Blame Dave.

### CODE REVIEW

**Comment by dsamojlenko** [comment]
I reformatted to get a cleaner diff .... looks like that i18n tool did some reorganizing.

Let's chat before merging this. Gotta come up with a good workflow for this stuff.

**Comment by keithiopia** [comment]
@dsamojlenko Shall I close this PR?

**Comment by CalvinRodo** [comment]
@dsamojlenko It looks like it just sorted the keys alphabetically, I think that's a good thing. I'm guessing the next PR won't have the issues this one will. 

Also we can probably add some sort of pre-commit hook that sorts so we can add junk to the bottom of localization files without worry about it getting modified later on.

**Comment by keithiopia** [comment]
After chatting to Dave, I'm going to close this PR. For one thing, my commit isn't signed!

**Pull request closed without merging**
