### PR TITLE
New treatments flow

### PR DESCRIPTION
**Pull request by dsamojlenko**
# What this does
- Allows you to generate new Conditions in-place on the Treatments form.
- Changes the layout of the Treatment form, changes some labels

## To review
- Start by filling out the personal section
- Either complete the next few steps, or skip ahead to `/en/treatments`
- You should get directed to the redesigned form.
- Under "Which condition(s) is this treatment for?" you'll be able to dynamically create conditions
  - Conditions created here will be automatically selected when this form is saved
  - We don't validate these fields, but we won't save any empty entries

## TODO (future): 
- need to do some a11y work on the dynamic fields
- the index screen currently directs to the Overall Health section, but should go to "dashboard" when that's available
- French

### CODE REVIEW

**Comment by CalvinRodo** [comment]
Should we not have a some way to notify the user that the condition is not completed when they navigate to the conditions page?

**Comment by CalvinRodo** [comment]
When adding a condition and hitting save I get an error saying "Please select at least one condition"

**Comment by dsamojlenko** [comment]
> Should we not have a some way to notify the user that the condition is not completed when they navigate to the conditions page?

Yeah, that'll come in a later PR .... we don't have a design for this right now

**Comment by dsamojlenko** [comment]
> When adding a condition and hitting save I get an error saying "Please select at least one condition"

hmmm... I'm not seeing this - it should be creating and selecting the condition before firing the validation - is this when conditions already exist? or none?

**Pull request merged**
